version: "3.3"

services:
  ubuntu:
    build:
      context: ./nto-server-files
    container_name: 1-Ubuntu-Server
    stdin_open: true
    tty: true
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./nto-server-files:/srv
    depends_on:
      - database

  spa:
    build:
      context: ./nto-web-spa
    container_name: 4-Next-Spa
    ports:
      - 3000:3000

  database:
    image: mysql:5.7
    container_name: 3-BancoDeDados
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: otserv
      MYSQL_PASSWORD: 1234
    volumes:
      - ./nto-server-files/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - my-network

  dbAdminPainel:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: 3-AdminBancoDeDados
    restart: always
    ports:
      - 1010:80
    links:
      - database
    environment:
      PMA_ARBITRARY: 1

  api:
    build:
      context: ./nto-web-api
    container_name: Api
    ports:
      - 3003:3003
    depends_on:
      - database
    networks:
      - my-network

networks:
  my-network:
