version: "3.3"

services:
  ubuntu:
    build:
      context: ./nto-server-files
    container_name: 1-Ubuntu-Server
    stdin_open: true
    tty: true
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./nto-server-files:/srv
    depends_on:
      - database

  site:
    build:
      context: ./nto-web-files
    container_name: 2-MyAcc-Site
    volumes:
      - ./nto-server-files/datapack:/srv
      - ./nto-web-files/html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - database
      - ubuntu

  database:
    image: mysql:5.7
    container_name: 3-BancoDeDados
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: otserv
      MYSQL_PASSWORD: 1234
    volumes:
      - ./nto-server-files/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  dbAdminPainel:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: 3-AdminBancoDeDados
    restart: always
    ports:
      - 1010:80
    links:
      - database
    environment:
      PMA_ARBITRARY: 1
